export type GastroskopiHeaderType = {
  header: string;
  d1: string;
  d2?: string;
  content: string;
  c1: string;
  c2: string;
  c3: string;
  c3c1: string;
  c3c2: string;
  c4: string;
  d3: string;
};

export type GastroskopiContentType = {
  h1: string;
  h1d1: string;
  h1d2: string;
  li11: string;
  li12: string;
  li13: string;
  li14: string;
  li15: string;
  li16: string;
  li17: string;
  li18: string;
  li19: string;
  d5: string;
  l21: string;
  l22: string;
  l23: string;
  l24: string;
  l25: string;
  l26: string;
  l27: string;
  l28: string;
  h2: string;
  h2d1: string;
  h2d2: string;
  h2d3: string;
  h2d4: string;
  h3: string;
  h3d1: string;
  h3d2: string;
  h3d3: string;
  h4: string;
  h4d1: string;
  h4d2: string;
};

export type GastroskopiFooterType = {
  h5: string;
  h5c1: string;
  h5d1: string;
  h5c2: string;
  h5d21: string;
  h5d22: string;
  h5c3: string;
  h5d3: string;
  h5c4: string;
  h5d4: string;
  h5c5: string;
  h5d5: string;
  h5c6: string;
  h5d6: string;
  h5c7: string;
  h5d7: string;
  h5c8: string;
  h5d8: string;
  h5c9: string;
  h5d9: string;
  h5c10: string;
  h5d10: string;
  h5c11: string;
  h5d11: string;
};

///////////////////////////////////////////////////

export type KolonoskopiHeaderType = {
  header: string;
  d1: string;
  content: string;
  c1: string;
  c2: string;
  c3: string;
  c4: string;
  c5: string;
  c5c1: string;
  c5c2: string;
  c6: string;
  c7: string;
};
export type KolonoskopiContentType = {
  h1: string;
  h1d1: string;
  h1d2: string;
  h1d3: string;
  lih1: string;
  lid1: string;
  lih2: string;
  lid2: string;
  lih3: string;
  lid3: string;
  lih4: string;
  lid4: string;
  h1d4: string;
  h1d5: string;
  h2: string;
  h2d1: string;
  h2d2: string;
  h3: string;
  h3d1: string;
  h3d2: string;
  h4: string;
  h4d1: string;
  h5: string;
  h5d1: string;
  h5d2: string;
  h6: string;
  h6d1: string;
  h6d2: string;
  h7: string;
  h7d1: string;
  h7d2: string;
  h7d3: string;
};

export type KolonoskopiFooterType = {
  h8: string;
  q1: string;
  a1: string;
  q2: string;
  a2: string;
  q3: string;
  a3: string;
  q4: string;
  a4: string;
  q5: string;
  a5: string;
  q6: string;
  a6: string;
  q7: string;
  a7: string;
  q8: string;
  a8: string;
  q9: string;
  a9: string;
  q10: string;
  a10: string;
  q11: string;
  a11: string;
  q12: string;
  a12: string;
  q13: string;
  a13: string;
};

export type SigmoidoskopiHeaderType = {
  header: string;
  d1: string;
  content: string;
  c1: string;
  c2: string;
  c3: string;
  c3c1: string;
  c3c2: string;
  c3c3: string;
  c4: string;
  d2: string;
  d3: string;
};

export type SigmoidoskopiContentType = {
  h1: string;
  h1d1: string;
  h1d2: string;
  h1d3: string;
  lih1: string;
  lid1: string;
  lih2: string;
  lid2: string;
  d4: string;
  h2: string;
  h2d1: string;
  h2d2: string;
  h3: string;
  h3d1: string;
  h4: string;
  h4d1: string;
  h4d2: string;
  h4d3: string;
  li1: string;
  li2: string;
  li3: string;
  d5: string;
  h5: string;
  h5d1: string;
  h6: string;
  h6d1: string;
  h6d2: string;
};


export type KapsulEndoskopiHeaderType = {
    header: string;
    d1: string;
    content: string;
    c1: string;
    c2: string;
    c3: string;
    c4: string;
    d2: string;
    d3: string;
    d4: string;
   
  };

  export type KapsulEndoskopiContentType = {
    h1: string;
    h1d1: string;
    li1: string;
    li2: string;
    li3: string;
    li4: string;
    li5: string;
    li6: string;
    li7: string;
    h2: string;
    h2d1: string;
    h2d2: string;
    h2d3: string;
    h3: string;
    h3d1: string;
    h3d2: string;
    h3d3: string;
    h3d4: string;
    h3d5: string;
    h3d6: string;
  }
